#ifndef GAMEFACTS_H
#define GAMEFACTS_H

#define WINDOWWIDTH 800
#define WINDOWHEIGHT 600

#define RATIO_DENOMINATOR 2

#define GAMEWIDTH (WINDOWWIDTH * 1 / RATIO_DENOMINATOR)
#define GAMEHEIGHT (WINDOWHEIGHT * 1 / RATIO_DENOMINATOR)

#endif